import { BLOWFISH_KEY_PACKET, BLOWFISH_KEY_AUTH } from './crypto-keys-constants.js';

const BLOWFISH_KEY_VIEW = new DataView(
  BLOWFISH_KEY_PACKET.buffer,
  BLOWFISH_KEY_PACKET.byteOffset,
  BLOWFISH_KEY_PACKET.byteLength
);

const BLOWFISH_AUTH_KEY_VIEW = new DataView(
  BLOWFISH_KEY_AUTH.buffer,
  BLOWFISH_KEY_AUTH.byteOffset,
  BLOWFISH_KEY_AUTH.byteLength
);

export { BLOWFISH_KEY_PACKET, BLOWFISH_KEY_AUTH, BLOWFISH_KEY_VIEW, BLOWFISH_AUTH_KEY_VIEW };
